---
title: "CodeBook"
author: "David Normann"
date: "6/21/2020"
output: html_document
---

## Introduction 
Each row (observation) in this dataset is the result of a unique combination of activity and subject resulting in a total of 180 observations. For each combination of activity and subject, the run_analysis.R script calculates a single average measurement for each of these 66 variables without regard to their original calculation purpose.

The criteria for selecting the 66 measurement variables (below) is based upon the course assignment's direction to only extract "on the mean and standard deviation for each measurement." It is from this extraction that the average calculation for each of the 180 unique combinations of activity and subject is applied.  


## Added variables to measurement data: 
The 180 unique combinations are specified by two columns of data: 

"activity" - one of six activities e.g, STANDING, SITTING, etc. 
"subject" - An ID associated with each of the 30 subjects involved in the original experiments. 

 
## Measurement variables: 
These variables were extracted from the original 561 variables detailed in the original README.txt and the features_info.txt files that were provided in the UCI HAR Dataset folder. 

 "tBodyAcc-mean()-X"
 "tBodyAcc-mean()-Y"
 "tBodyAcc-mean()-Z"
 "tGravityAcc-mean()-X"
 "tGravityAcc-mean()-Y"
 "tGravityAcc-mean()-Z"       
 "tBodyAccJerk-mean()-X"
 "tBodyAccJerk-mean()-Y"      
"tBodyAccJerk-mean()-Z"
"tBodyGyro-mean()-X"         
"tBodyGyro-mean()-Y"
"tBodyGyro-mean()-Z"         
"tBodyGyroJerk-mean()-X"
"tBodyGyroJerk-mean()-Y"     
"tBodyGyroJerk-mean()-Z"
"tBodyAccMag-mean()"         
"tGravityAccMag-mean()"
"tBodyAccJerkMag-mean()"     
"tBodyGyroMag-mean()"
"tBodyGyroJerkMag-mean()"    
"fBodyAcc-mean()-X"
"fBodyAcc-mean()-Y"          
"fBodyAcc-mean()-Z"
"fBodyAccJerk-mean()-X"      
"fBodyAccJerk-mean()-Y"
"fBodyAccJerk-mean()-Z"      
"fBodyGyro-mean()-X"
"fBodyGyro-mean()-Y"         
"fBodyGyro-mean()-Z"
"fBodyAccMag-mean()"         
"fBodyBodyAccJerkMag-mean()"
"fBodyBodyGyroMag-mean()"    
"fBodyBodyGyroJerkMag-mean()"
"tBodyAcc-std()-X"           
"tBodyAcc-std()-Y"
"tBodyAcc-std()-Z"           
"tGravityAcc-std()-X"
"tGravityAcc-std()-Y"        
"tGravityAcc-std()-Z" 
"tBodyAccJerk-std()-X"       
"tBodyAccJerk-std()-Y" 
"tBodyAccJerk-std()-Z"       
"tBodyGyro-std()-X" 
"tBodyGyro-std()-Y"          
"tBodyGyro-std()-Z"  
"tBodyGyroJerk-std()-X"      
"tBodyGyroJerk-std()-Y"
"tBodyGyroJerk-std()-Z"      
"tBodyAccMag-std()"
"tGravityAccMag-std()"       
"tBodyAccJerkMag-std()"
"tBodyGyroMag-std()"         
"tBodyGyroJerkMag-std()"
"fBodyAcc-std()-X"           
"fBodyAcc-std()-Y" 
"fBodyAcc-std()-Z"           
"fBodyAccJerk-std()-X" 
"fBodyAccJerk-std()-Y"       
"fBodyAccJerk-std()-Z"
"fBodyGyro-std()-X"          
"fBodyGyro-std()-Y"
"fBodyGyro-std()-Z"          
"fBodyAccMag-std()" 
"fBodyBodyAccJerkMag-std()"  
"fBodyBodyGyroMag-std()"
"fBodyBodyGyroJerkMag-std()" 
