---
title: "README"
author: "tokidokig"
date: "6/19/2020"
output: html_document
---

# run_analysis.R script 
The run_analysis.R script produces a dataset of 180 observations and 68 variables. Two variables combine to produce the 180 unique combinations of activity and subject. For each of these unique combinations, the average of 66 selected measurement variables are calculated. 

The 66 measurement variables were selected from the total possible list of measurement variables in the original UCI HAR Dataset because they relate to mean and standard deviation. 

It is important to emphasize that the run_analysis.R script calculates a single average measurement for each of these 66 variables without regard to their original calculation purpose. 


## Script output and location 
This run_analysis.R script is designed to run in the same working directory as the UCI HAR Dataset folder that was provided by the course.

In addition to producing the final processed data (indepTidyAvg), the script also writes out the data to independent_tidy_average.txt in the working directory. 


## Script functions:  

1. Merges data as follows: 
    + Core measurements files from the UCI HAR Dataset folder: 
        + X_test.txt
        + X_train.txt
        + y_test.txt
        + y_train.txt
    + Adds column headers (variable names) to these merged core measurements based upon data in UCI HAR Dataset folder: 
        + features.txt 
    + For each measurement, additional columns were added to clarify activity and subject. From the UCI HAR Dataset folder, the following files were used to source this data: 
        + activity_labels.txt 
        + subject_test.txt 
        + subject_train.txt 
2. Subsets the above merged data to extracts only the mean and standard deviation for each measurement row (observation). 
3. Adds a column of descriptive activity names 
4. Retains source descriptive names for each variable 
5. Creates a second tidy data set with the average of each activity and each subject. 


## R and Package versions used 

R version 3.6.2 (2019-12-12)

Tidyverse 1.3.0 

Tidyverse sub packages: 
✓ ggplot2 3.2.1     ✓ purrr   0.3.3
✓ tibble  2.1.3     ✓ dplyr   0.8.4
✓ tidyr   1.0.2     ✓ stringr 1.4.0
✓ readr   1.3.1     ✓ forcats 0.5.0


## Additional files and information 

1. run_analysis.R - data processing script 
2. CodeBook.Rmd - variables added or drawn from the course project data 
3. features_info.txt - source list of variables from course project folder 
4. Original README.txt from course project information folder  




